import {
  Package, ShoppingBag, Laptop, Smartphone, Monitor, Tv, Headphones, Camera,
  Shirt, Home, Coffee, Utensils, Heart, Book, BookOpen, Music, Car, Dumbbell,
  Tag, Star, Gift, Box, Globe, Sparkles, Zap, Bike, Pizza, Watch, Wrench,
  Scissors, Flower2, Dog, Baby, Gamepad2, Pill, Sofa, Lamp, Apple, type LucideIcon,
} from "lucide-react";

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  package:    Package,
  shoppingbag: ShoppingBag,
  laptop:     Laptop,
  smartphone: Smartphone,
  monitor:    Monitor,
  tv:         Tv,
  headphones: Headphones,
  camera:     Camera,
  shirt:      Shirt,
  home:       Home,
  coffee:     Coffee,
  utensils:   Utensils,
  heart:      Heart,
  book:       Book,
  bookopen:   BookOpen,
  music:      Music,
  car:        Car,
  dumbbell:   Dumbbell,
  tag:        Tag,
  star:       Star,
  gift:       Gift,
  box:        Box,
  globe:      Globe,
  sparkles:   Sparkles,
  zap:        Zap,
  bike:       Bike,
  pizza:      Pizza,
  watch:      Watch,
  wrench:     Wrench,
  scissors:   Scissors,
  flower2:    Flower2,
  dog:        Dog,
  baby:       Baby,
  gamepad2:   Gamepad2,
  pill:       Pill,
  sofa:       Sofa,
  lamp:       Lamp,
  apple:      Apple,
};

export const ICON_LABELS: Record<string, string> = {
  package:    "General",
  shoppingbag:"Tienda",
  laptop:     "Laptop",
  smartphone: "Celular",
  monitor:    "Monitor",
  tv:         "TV",
  headphones: "Audio",
  camera:     "Cámara",
  shirt:      "Ropa",
  home:       "Hogar",
  coffee:     "Café",
  utensils:   "Comida",
  heart:      "Salud",
  book:       "Libro",
  bookopen:   "Lectura",
  music:      "Música",
  car:        "Autos",
  dumbbell:   "Gym",
  tag:        "Ofertas",
  star:       "Premium",
  gift:       "Regalos",
  box:        "Envíos",
  globe:      "Import.",
  sparkles:   "Lujo",
  zap:        "Electr.",
  bike:       "Bicicleta",
  pizza:      "Delivery",
  watch:      "Relojes",
  wrench:     "Herram.",
  scissors:   "Belleza",
  flower2:    "Flores",
  dog:        "Mascotas",
  baby:       "Bebés",
  gamepad2:   "Juegos",
  pill:       "Farmacia",
  sofa:       "Muebles",
  lamp:       "Ilum.",
  apple:      "Frutas",
};

export function getCategoryIcon(iconName: string | null | undefined): LucideIcon {
  if (!iconName) return Package;
  return CATEGORY_ICONS[iconName.toLowerCase()] ?? Package;
}
